version: "3.9"
services:
  redis:
    image: "redis:alpine"
    networks:
      - prone_network

  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: prone
    networks:
      - prone_network

  app:
    image: golang:1.20
    volumes:
      - ${PWD}:/app
    working_dir: /app
    # command: go run main.go
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - prone_network

networks:
  prone_network:
